version: "3.7"

services:
  server:
    image: nginx
    restart: always
    env_file: stack.env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - /volume1/docker/invoiceninja/config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - /volume1/docker/invoiceninja/app/public:/var/www/app/public:ro
    depends_on:
      - invoiceninja
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports:
      - "9001:80"
      #- "443:443"
    networks:
      - invoiceninja

  invoiceninja:
    image: invoiceninja/invoiceninja:5
    env_file: stack.env
    restart: always
    volumes:
      - /volume1/docker/invoiceninja/config/hosts:/etc/hosts:ro
      - /volume1/docker/invoiceninja/app/public:/var/www/app/public:rw,delegated
      - /volume1/docker/invoiceninja/app/storage:/var/www/app/storage:rw,delegated
      - /volume1/docker/invoiceninja/config/php/php.ini:/usr/local/etc/php/php.ini
      - /volume1/docker/invoiceninja/config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
    depends_on:
      - invoiceninja-db
    networks:
      - invoiceninja

  invoiceninja-db:
    image: mysql:8
    #    When running on ARM64 use MariaDB instead of MySQL
    #    image: mariadb:10.4
    #    For auto DB backups comment out image and use the build block below
    #    build:
    #      context: ./config/mysql
    ports:
      - "3307:3306"
    restart: always
    env_file: stack.env
    user: 1026:100
    volumes:
      - /volume1/docker/invoiceninja/data/mysql:/var/lib/mysql:rw,delegated
      # remove comments for next 4 lines if you want auto sql backups
      # - ./data/bak:/backups:rw
      # - ./config/mysql/backup-script:/etc/cron.daily/daily:ro
      # - ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
      # - ./config/mysql/backup-script:/etc/cron.monthly/monthly:ro
    networks:
      - invoiceninja

networks:
  invoiceninja:
