version: '3'

services:
  bind9:
    container_name: idl-dns
    image: ubuntu/bind9
    environment:
      - BIND9_USER=root
      - TZ=Asia/Singapore
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: always