version: '3.7'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_DEV_NAME
      MYSQL_USER: $DB_DEV_USERNAME
      MYSQL_PASSWORD: $DB_DEV_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_DEV_R_PWD
      MYSQL_ROOT_HOST: $DB_DEV_HOST
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
volumes:
  db_data:
